// Mocks generated by Mockito 5.4.6 from annotations
// in primo_v2/test/features/auth/presentation/bloc/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:primo_v2/core/entities/employee_entity.dart' as _i8;
import 'package:primo_v2/core/error/failures.dart' as _i7;
import 'package:primo_v2/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:primo_v2/features/auth/domain/usecases/login_with_pin_usecase.dart'
    as _i5;
import 'package:primo_v2/features/employees/domain/entities/work_shift_entity.dart'
    as _i10;
import 'package:primo_v2/features/employees/domain/repositories/work_shift_repository.dart'
    as _i4;
import 'package:primo_v2/features/employees/domain/usecases/clock_in_usecase.dart'
    as _i11;
import 'package:primo_v2/features/employees/domain/usecases/get_active_work_shift_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWorkShiftRepository_2 extends _i1.SmartFake
    implements _i4.WorkShiftRepository {
  _FakeWorkShiftRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginWithPinUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithPinUseCase extends _i1.Mock
    implements _i5.LoginWithPinUseCase {
  MockLoginWithPinUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.EmployeeEntity>> call(String? pin) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [pin],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i8.EmployeeEntity>>.value(
                _FakeEither_1<_i7.Failure, _i8.EmployeeEntity>(
          this,
          Invocation.method(
            #call,
            [pin],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i8.EmployeeEntity>>);
}

/// A class which mocks [GetActiveWorkShiftUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetActiveWorkShiftUseCase extends _i1.Mock
    implements _i9.GetActiveWorkShiftUseCase {
  MockGetActiveWorkShiftUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.WorkShiftRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkShiftRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.WorkShiftRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity?>> call(
          _i9.GetActiveWorkShiftParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity?>>.value(
                _FakeEither_1<_i7.Failure, _i10.WorkShiftEntity?>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity?>>);
}

/// A class which mocks [LaborClockInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLaborClockInUseCase extends _i1.Mock
    implements _i11.LaborClockInUseCase {
  MockLaborClockInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.WorkShiftRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkShiftRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.WorkShiftRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity>> call(
          _i11.LaborClockInParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity>>.value(
                _FakeEither_1<_i7.Failure, _i10.WorkShiftEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i6.Future<_i3.Either<_i7.Failure, _i10.WorkShiftEntity>>);
}
